services:
    database:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        command: mysqld
        volumes:
            - dev-db:/var/lib/mysql
    database-explorer:
        image: phpmyadmin
        restart: always
        ports:
            - 8036:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: ${DB_PASSWORD}

volumes:
    dev-db:
